[package]
name = "multi-bomb-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.10", features = ["ws"] }
axum-macros = "0.3.5"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread", "signal"] }
